### ISSUE TITLE
Build failing in Android using phonegap build

### ISSUE THREAD

**Issue by butlimous** [Wizcorp/phonegap-facebook-plugin#1018]
Hi,

Starting from yesterday, suddenly I'm getting the following error and the build is failing in Android when using PhoneGap Build:

/home/ec2-user/android-sdk/tools/ant/build.xml:601: The following error occurred while executing this line:
/project/com.phonegap.plugins.facebookconnect/xxxxx-FacebookLib/build.xml:46: sdk.dir is missing. Make sure to generate local.properties using 'android update project' or to inject it through an env var

It's working in iOS though!

**Comment by dhatawesomedude** [comment]
+1 Having same issue too, today. It was working well yesterday.

**Comment by MaliciousMustard** [comment]
+1 Same issue here!!!

**Comment by thedarkman123** [comment]
+1

**Comment by thedarkman123** [comment]
OMG i have a deadline for tomorrow and this plugin just crashed all my work, please help

**Comment by butlimous** [comment]
@thedarkman123 in the meantime, you can use version 3.5.0 of the plugin by adding version = '3.5.0' to your config.xml. It should be working with this version

**Comment by thedarkman123** [comment]
Which plugin 3.5.0? the phonegap/cordova?

**Comment by dhatawesomedude** [comment]
@butlimous I tried changing phonegap to 3.5.0; still doesn't work.

**Comment by thedarkman123** [comment]
yep it still doesn't

**Comment by thedarkman123** [comment]
it falls back to the iframe version of it and it sucks

**Comment by butlimous** [comment]
@dhatawesomedude I haven't tested this temp solution. I got it from one of the comments in this link http://community.phonegap.com/nitobi/topics/builds-in-ios-not-in-android-havent-had-any-issues-before-with-this

@thedarkman123 Add the following to your config.xml and see if it works:
 <preference name="phonegap-version" value="3.5.0"/>

**Comment by dhatawesomedude** [comment]
Btw, this has crashed for ios as well.

**Comment by thedarkman123** [comment]
We need this fixed right away plz guys! 3.5.0 is not the solution, already tried it, the plugin just doesn't work well (connecting with iframe which looks like crap when landscape)... any developments?
what we are the only three 4 people who have that issue?

**Comment by batman11111** [comment]
Having same issue..  It won't use the native facebook app to login on iOS or Android.  Tried building with PG Build 3.7, 3.6.3 and 3.5.  Was working early yesterday.

**Comment by thedarkman123** [comment]
yep me too, started not long ago, and its a real pain in the ***, what can be the cause of this?

**Comment by thedarkman123** [comment]
+10

**Comment by thedarkman123** [comment]
Anything? workaround? something? anyone?

**Comment by butlimous** [comment]
It's a phonegap build issue. They should be working on it but don't know when it would be fixed :(

**Comment by thedarkman123** [comment]
You telling me this is not something to do with the facebook plugin but with phonegap build itself? let's do something in the support over there, this is very serious issue..

**Comment by butlimous** [comment]
There are already multiple threads in the official phonegap support about it:
http://community.phonegap.com/nitobi/topics/android-builds-not-working
http://community.phonegap.com/nitobi/topics/builds-in-ios-not-in-android-havent-had-any-issues-before-with-this
http://community.phonegap.com/nitobi/topics/facebook-connect-issue-with-phonegap-build

An employee replied in one of the above asking for affected app ids from few hours but still no fix :( I don't know why it's taking them this long!

**Comment by winstef** [comment]
Same issue here for ios, it opens up the popup instead of the native app for login.
I really hope they fix it soon.

**Comment by thedarkman123** [comment]
Still problem with the popup persist, breaks my app, any progress on this matter?

**Comment by thedarkman123** [comment]
This issue should mark as solved, the other one is the problem (popup stuff)
